groups:
- name: build
  jobs:
  - testflight
  - rc
  - shipit
- name: version
  jobs:
  - patch
  - minor
  - major

jobs:
- name: testflight
  public: false
  serial: true
  plan:
  - do:
    - aggregate:
      - get: chronograf-boshrelease
        resource: git-chronograf-boshrelease
      - get: git-chronograf-boshrelease-release-changes
        trigger: false
    - task: create-release-and-deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((docker.image))
        inputs:
        - {name: chronograf-boshrelease}
        run:
          path: ./chronograf-boshrelease/ci/scripts/create_release_and_deploy.sh
          args: []
        params:
          bosh_target: ((bosh-lite-build.target))
          bosh_username: ((bosh-lite-build.username))
          bosh_password: ((bosh-lite-build.password))
          bosh_deployment_name: chronograf-warden

- name: rc
  public: false
  plan:
  - aggregate:
    - get: boshrelease
      resource: git-chronograf-boshrelease
      passed: [testflight]
      trigger: true
    - get: version
      trigger: false
      params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}

- name: patch
  public: false
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: patch}
  - put: version
    params: {file: version/number}

- name: minor
  public: false
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: minor}
  - put: version
    params: {file: version/number}

- name: major
  public: false
  plan:
  - aggregate:
    - get: version
      trigger: false
      params: {bump: major}
  - put: version
    params: {file: version/number}

- name: shipit
  public: false
  serial: true
  plan:
  - aggregate:
    - get: version
      passed: [rc]
      params: {bump: final}
    - get: boshrelease
      resource: git-chronograf-boshrelease
      passed: [rc]
  - task: create-final-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((docker.image))
      inputs:
      - {name: boshrelease, path: chronograf-boshrelease}
      - {name: version}
      outputs:
      - {name: create-final-release, path: output}
      run:
        path: ./chronograf-boshrelease/ci/scripts/shipit.sh
        args: []
      params:
        release_name: "chronograf BOSH release"
        bosh_target: ((bosh-lite-build.target))
        bosh_username: ((bosh-lite-build.username))
        bosh_password: ((bosh-lite-build.password))
        bosh_deployment_name: chronograf-warden
        aws_access_key_id: ((user-aws-concourse.aws_access_key))
        aws_secret_access_key: ((user-aws-concourse.aws_secret_key))
        promotion_branch: master
        output_dir: ../output/chronograf-boshrelease
  - put: git-chronograf-boshrelease
    params:
      repository: create-final-release/chronograf-boshrelease
      rebase: true
  - aggregate:
    - put: version
      params: {file: version/number}
    - put: final-release
      params:
        from: create-final-release/chronograf-boshrelease/releases/chronograf/chronograf-(.*).tgz
        to: chronograf-boshrelease/
    - put: github-final-release
      params:
        name: create-final-release/chronograf-boshrelease/release/name
        tag: create-final-release/chronograf-boshrelease/release/tag
        body: create-final-release/chronograf-boshrelease/release/notes.md
        globs: [create-final-release/chronograf-boshrelease/releases/chronograf/chronograf-*.tgz]

resources:
- name: version
  type: semver
  source:
    key: current-version
    bucket: ((s3.pipeline-bucket))
    access_key_id: ((user-aws-concourse-idefixoperationsprod.aws_access_key))
    secret_access_key: ((user-aws-concourse-idefixoperationsprod.aws_secret_key))
    initial_version: 0.0.0

- name: git-chronograf-boshrelease
  type: git
  source:
    uri: ((git.uri))
    branch: ((git.branch))

- name: git-chronograf-boshrelease-release-changes
  type: git
  source:
    uri: ((git.uri))
    branch: ((git.branch))
    paths:
      - src/**/*
      - jobs/**/*
      - packages/**/*
      - config/blobs.yml
      - .final_builds/**/*
      - templates/**/*
      - .gitmodules

- name: github-final-release
  type: github-release
  source:
    user: hybris
    repository: chronograf-boshrelease
    access_token: ((github.accessToken))

- name: final-release
  type: s3
  source:
    bucket: ((s3-buckets.boshreleases))
    regexp: chronograf-boshrelease/chronograf-(.*).tgz
    access_key_id: ((user-aws-concourse.aws_access_key))
    secret_access_key: ((user-aws-concourse.aws_secret_key))
